'use client'

import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'

import {
  createStrategyDefinitionAction,
  validateStrategyJsonAction,
} from '@/app/actions/strategy-definitions'
import { Button } from '@/components/ui/Button'
import { Dialog } from '@/components/ui/Dialog'
import type { StrategyDefinition } from '@/lib/strategies/types'

export type JsonPasteModalProps = {
  open: boolean
  onClose: () => void
}

// Power-user entry point: paste a strategy_definition JSON
// document, validate it (calls the same zod entry the action
// layer uses), and save. Useful when a strategy was authored
// outside the visual builder, e.g. shared from another operator
// or generated by tooling.
export function JsonPasteModal({ open, onClose }: JsonPasteModalProps) {
  const router = useRouter()
  const [isPending, startTransition] = useTransition()
  const [text, setText] = useState('')
  const [errors, setErrors] = useState<string[]>([])
  const [parsed, setParsed] = useState<StrategyDefinition | null>(null)

  function reset() {
    setText('')
    setErrors([])
    setParsed(null)
  }

  function handleClose() {
    reset()
    onClose()
  }

  function handleValidate() {
    setErrors([])
    setParsed(null)
    startTransition(async () => {
      const result = await validateStrategyJsonAction(text)
      if (!result.ok) {
        setErrors(result.errors)
        return
      }
      setParsed(result.parsed)
    })
  }

  function handleSave() {
    if (!parsed) return
    startTransition(async () => {
      const result = await createStrategyDefinitionAction(
        parsed.name,
        null,
        parsed,
      )
      if (!result.ok) {
        setErrors([result.message ?? 'Save failed'])
        return
      }
      handleClose()
      router.push(`/settings/strategies/${result.row.id}`)
      router.refresh()
    })
  }

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      title="Paste strategy JSON"
      description="Paste a complete strategy_definition document. Validation runs against the same schema as the visual builder."
      className="max-w-2xl"
      footer={
        <>
          <Button
            type="button"
            variant="ghost"
            onClick={handleClose}
            className="w-auto"
            disabled={isPending}
          >
            Cancel
          </Button>
          <Button
            type="button"
            variant="ghost"
            onClick={handleValidate}
            className="w-auto"
            disabled={isPending || text.trim().length === 0}
          >
            Validate
          </Button>
          <Button
            type="button"
            onClick={handleSave}
            className="w-auto"
            disabled={isPending || !parsed}
          >
            {isPending ? 'Saving…' : 'Save strategy'}
          </Button>
        </>
      }
    >
      <textarea
        value={text}
        onChange={(event) => {
          setText(event.target.value)
          setParsed(null)
          setErrors([])
        }}
        rows={14}
        spellCheck={false}
        className="w-full rounded-md border border-white/10 bg-transparent p-3 font-mono text-xs text-white/85 outline-none focus:border-accent focus:ring-1 focus:ring-accent"
        placeholder='{ "schema_version": 1, "name": "...", "direction": "long_only", "entry": { ... }, "exit": { ... }, "sizing": { ... } }'
      />
      {errors.length > 0 ? (
        <ul className="mt-3 flex flex-col gap-1 rounded-md border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-200">
          {errors.map((err, i) => (
            <li key={i} className="font-mono">
              {err}
            </li>
          ))}
        </ul>
      ) : null}
      {parsed ? (
        <div className="mt-3 rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-200">
          <div className="font-medium">{parsed.name}</div>
          <div className="mt-1 text-emerald-200/80">
            {parsed.direction} · {parsed.entry.groups.length}{' '}
            {parsed.entry.groups.length === 1 ? 'group' : 'groups'} ·{' '}
            {parsed.entry.groups.reduce(
              (sum, g) => sum + g.conditions.length,
              0,
            )}{' '}
            conditions · stop {parsed.exit.stop.type} · target{' '}
            {parsed.exit.target.type} · sizing {parsed.sizing.type}
          </div>
        </div>
      ) : null}
    </Dialog>
  )
}
